# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python server script to the container
COPY simple-http-server.py .

# Expose the port on which the server runs
EXPOSE 8000

# Run the server
CMD ["python3", "simple-http-server.py"]
