version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - "8000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - server_network

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:rw"
    depends_on:
      - server
    networks:
      - server_network

networks:
  server_network:
    driver: bridge
